# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: myhostedagent

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Dev(b7cda313-770f-4cf7-89fd-81621c3709fd)'
    appType: 'webApp'
    appName: 'oneidas3'
    package: '$(System.DefaultWorkingDirectory)/*.zip'
    deploymentMethod: 'auto'

